openapi: 3.0.1
info:
  title: Loopio
  description: Loopio's Public API
  termsOfService: 'http://loopio.com/termsOfService'
  contact:
    email: support@loopio.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0
servers:
  - url: 'https://api.loopio.com/data/v2'
    description: Production server for the American datacenter
  - url: 'https://api.eu.loopio.com/data/v2'
    description: Production server for the European datacenter
tags:
  - name: Asynchronous
    description: An asynchronous endpoint
  - name: Customers
    description: Get information about Customer instances
  - name: Custom Project Fields
    description: Create and manage Custom Project Fields
  - name: Files
    description: Manage Loopio files
  - name: Merge Variables
    description: Reusable Library/Project-wide variables
  - name: Library Entries
    description: Create and manage Library Entries
  - name: Projects
    description: Create and manage Projects
  - name: Project Templates
    description: Get Information about Project Templates
  - name: Stacks
    description: View accessible stacks or Library structure
  - name: Users
    description: Create and manage Users
  - name: Teams
    description: Get Information about Teams
  - name: Webhooks
    description: Create & Manage webhook subscriptions
paths:
  '/customers/{customerId}/activeLanguages':
    get:
      tags:
        - Customers
      summary: Get all the languages in use in a customer's collection of library entries
      operationId: getCustomerActiveLanguages
      security:
        - loopio_auth:
            - 'customer.info:read'
  '/customers/{customerId}':
    get:
      tags:
        - Customers
      summary: Get the id and guid for a given Customer
      operationId: getCustomer
      security:
        - loopio_auth:
            - 'customer.info:read'
  '/files/{fileId}':
    get:
      tags:
        - Files
      summary: Show information about a file
      operationId: showFile
      security:
        - loopio_auth:
            - 'file:read'
    delete:
      tags:
        - Files
      summary: Delete a file
      description: 'If this file is linked with any other Loopio resources, that link will also be deleted'
      operationId: deleteFile
      security:
        - loopio_auth:
            - 'file:delete'
  '/crm/{opportunityID}/projects':
    get:
      tags:
        - CRM
      summary: Get the list of viewable Projects associated with a given CRM Opportunity
      operationId: listCRMProjects
      security:
        - loopio_auth:
            - 'crm:read'
  /libraryEntries:
    get:
      tags:
        - Library Entries
      summary: List Library Entries you can interact with
      operationId: listLibraryEntries
      security:
        - loopio_auth:
            - 'library:read'
    post:
      tags:
        - Library Entries
      summary: Create a Library Entry
      description: |-
        Answer text for an Entry can be null if its Questions have Compliance Answers.
        Note: we are making terminology updates in Loopio - Compliance Sets shall be referred to as Answer Sets. The API will be updated to reflect this change at a later time.
      operationId: createLibraryEntry
      security:
        - loopio_auth:
            - 'library:write'
  /libraryEntries/bulk:
    post:
      tags:
        - Library Entries
        - Asynchronous
      summary: Bulk create Library Entries
      description: |-
        Answer text for an Entry can be null if its Questions have Compliance Answers.
        Note: we are making terminology updates in Loopio - Compliance Sets shall be referred to as Answer Sets. The API will be updated to reflect this change at a later time.
      operationId: bulkCreateLibraryEntries
      security:
        - loopio_auth:
            - 'library:write'
  '/libraryEntries/{libraryEntryId}':
    get:
      tags:
        - Library Entries
      summary: Get a Library Entry
      operationId: getLibraryEntry
      security:
        - loopio_auth:
            - 'library:read'
    patch:
      tags:
        - Library Entries
      summary: Update core properties of a Library Entry
      operationId: updateLibraryEntry
      security:
        - loopio_auth:
            - 'library:write'
    delete:
      tags:
        - Library Entries
      operationId: deleteLibraryEntry
      security:
        - loopio_auth:
            - 'library:delete'
  '/libraryEntries/{libraryEntryId}/attachments':
    get:
      tags:
        - Library Entries
      summary: Get Library Entry's Attachments
      operationId: getLibraryEntryFiles
      security:
        - loopio_auth:
            - 'library:read'
  '/libraryEntryHistories/{libraryEntryId}':
    get:
      tags:
        - Library Entries
      summary: Get history of a Library Entry
      operationId: getLibraryEntryHistories
      security:
        - loopio_auth:
            - 'library:read'
  '/libraryEntryHistories/{libraryEntryId}/{historyId}':
    get:
      tags:
        - Library Entries
      summary: Get a specific history item of a Library Entry
      operationId: getLibraryEntryHistory
      security:
        - loopio_auth:
            - 'library:read'
  /stacks:
    get:
      tags:
        - Stacks
      summary: List accessible stacks; View full Library structure
      operationId: listStacks
      security:
        - loopio_auth:
            - 'library:read'
  '/asyncTasks/mergeVariableDelete/{taskId}':
    get:
      tags:
        - Asynchronous
        - Merge Variables
      summary: Get the status of Merge Variable deletion request
      operationId: getMegeVariableDeleteStatus
  /mergeVariables:
    get:
      tags:
        - Merge Variables
      summary: List defined Merge Variables
      operationId: listMergeVariables
      security:
        - loopio_auth:
            - 'mergeVariable:read'
    post:
      tags:
        - Merge Variables
      summary: Create a new Merge Variable
      operationId: createMergeVariable
      security:
        - loopio_auth:
            - 'mergeVariable:write'
  '/mergeVariables/{id}':
    get:
      tags:
        - Merge Variables
      summary: Get a Merge Variable
      operationId: getMergeVariable
      security:
        - loopio_auth:
            - 'mergeVariable:read'
    patch:
      tags:
        - Merge Variables
      summary: Update a Merge Variable
      operationId: updateMergeVariable
      security:
        - loopio_auth:
            - 'mergeVariable:write'
    delete:
      tags:
        - Merge Variables
      summary: Delete a Merge Variable
      operationId: deleteMergeVariable
      security:
        - loopio_auth:
            - 'mergeVariable:delete'
  '/mergeVariables/{id}/history':
    get:
      tags:
        - Merge Variables
      summary: Get a Merge Variable's history
      operationId: getMergeVariableHistory
      security:
        - loopio_auth:
            - 'mergeVariable:read'
  '/projects/{projectId}/complianceSets':
    get:
      tags:
        - Projects
      summary: Get the Compliance Sets for a Project
      description: |-
        Note: Confidential projects are currently not supported via API.

         Note: We are making terminology updates in Loopio - Compliance Sets shall be referred to as Answer Sets. The API will be updated to reflect this change at a later time.
      operationId: getProjectComplianceSets
    post:
      tags:
        - Projects
      summary: Create a Compliance Set for a Project
      description: |-
        Note: Confidential projects are currently not supported via API.

         Note: We are making terminology updates in Loopio - Compliance Sets shall be referred to as Answer Sets. The API will be updated to reflect this change at a later time.
      operationId: createComplianceSet
  '/projects/{projectId}/complianceSets/{complianceSetId}':
    get:
      tags:
        - Projects
      summary: Get a Compliance Set for a Project
      description: |-
        Note: Confidential projects are currently not supported via API.

         Note: We are making terminology updates in Loopio - Compliance Sets shall be referred to as Answer Sets.  The API will be updated to reflect this change at a later time.
      operationId: getProjectComplianceSet
    put:
      tags:
        - Projects
      summary: Update a Compliance Set for a Project
      description: |-
        Note: Confidential projects are currently not supported via API.

         Note: We are making terminology updates in Loopio - Compliance Sets shall be referred to as Answer Sets. The API will be updated to reflect this change at a later time.
      operationId: updateProjectComplianceSet
    delete:
      tags:
        - Projects
      summary: Delete a Compliance Set for a Project
      description: |-
        Note: Confidential projects are currently not supported via API.

         Note: We are making terminology updates in Loopio - Compliance Sets shall be referred to as Answer Sets. The API will be updated to reflect this change at a later time.
      operationId: deleteProjectComplianceSet
  /projects:
    get:
      tags:
        - Projects
      summary: List projects you can interact with
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: listProjects
      security:
        - loopio_auth:
            - 'project:read'
    post:
      tags:
        - Projects
      summary: Create a project
      operationId: createProject
      security:
        - loopio_auth:
            - 'project:write'
  '/projects/{projectId}':
    get:
      tags:
        - Projects
      summary: Get a Project's data
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: getProject
      security:
        - loopio_auth:
            - 'project:read'
    put:
      tags:
        - Projects
      summary: Update a Project's status
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: updateProject
      security:
        - loopio_auth:
            - 'project:write'
    delete:
      tags:
        - Projects
      summary: Delete a Project and its data
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: deleteProject
      security:
        - loopio_auth:
            - 'project:delete'
  '/projects/{projectId}/customProjectFields':
    get:
      tags:
        - Projects
        - Custom Project Fields
      summary: Get Custom Project Field values for a given Project
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: getCustomProjectFieldValuesForProject
      security:
        - loopio_auth:
            - 'project:read'
    patch:
      tags:
        - Projects
        - Custom Project Fields
      summary: Edit Custom Project Field values for a given Project
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: setCustomProjectFieldValuesForProject
      security:
        - loopio_auth:
            - 'project:write'
  '/projects/{projectId}/mergeVariables':
    get:
      tags:
        - Projects
        - Merge Variables
      summary: Get Project Merge Variable values for a Project
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: getMergeVariableValuesForProject
      security:
        - loopio_auth:
            - 'project:read'
            - 'mergeVariable:read'
    patch:
      tags:
        - Projects
        - Merge Variables
      summary: Edit the values of Project Merge Variables for a Project
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: setMergeVariableValuesForProject
      security:
        - loopio_auth:
            - 'project:write'
            - 'mergeVariable:write'
  '/projects/{projectId}/summary':
    get:
      tags:
        - Projects
      summary: Get the status summary of a Project
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: getProjectSummary
      security:
        - loopio_auth:
            - 'project:read'
  /projects/summary:
    get:
      tags:
        - Projects
      summary: Get the status summary list of Projects filtered by date last synced
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: getProjectSummaryList
      security:
        - loopio_auth:
            - 'project:read'
  '/projects/{projectId}/sourceDocuments':
    post:
      tags:
        - Projects
        - Files
      summary: Attach a source document to a Loopio Project
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: addProjectSourceDocument
      security:
        - loopio_auth:
            - 'project:write'
    get:
      tags:
        - Projects
        - Files
      summary: View basic information on a Project's source files
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: listProjectSourceDocuments
      security:
        - loopio_auth:
            - 'project:read'
  '/projects/{projectId}/opportunityLink':
    post:
      tags:
        - Projects
        - CRM
      summary: Link a Loopio Project and CRM Opportunity
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: createOpportunityLink
      security:
        - loopio_auth:
            - 'crm:write'
  '/projects/{projectId}/participants':
    get:
      tags:
        - Projects
      summary: Get the participants for a Project
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: getProjectParticipants
      security:
        - loopio_auth:
            - 'project.participant:read'
    put:
      tags:
        - Projects
      summary: Update the participants for a Project
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: updateProjectParticipants
      security:
        - loopio_auth:
            - 'project.participant:write'
  '/projectTemplates/{projectTemplateId}/projects':
    post:
      tags:
        - Projects
      summary: Create a project using a template (This creates an async task to execute this operation)
      description: 'Returns a taskId and a projectId. Make a GET request to /asyncTasks/{taskId}/projectTemplateCopy to find the status of the task.'
      operationId: createProjectFromTemplate
      security:
        - loopio_auth:
            - 'project:write'
  /projectTemplates:
    get:
      tags:
        - Project Templates
      summary: Get a list of published project templates
      operationId: listProjectTemplates
      security:
        - loopio_auth:
            - 'project:read'
  /customProjectFields:
    get:
      tags:
        - Custom Project Fields
      summary: List defined Custom Project Fields
      operationId: listCustomProjectFields
      security:
        - loopio_auth:
            - 'customProjectField:read'
    post:
      tags:
        - Custom Project Fields
      summary: Create a new Custom Project Field
      operationId: createCustomProjectField
      security:
        - loopio_auth:
            - 'customProjectField:write'
  '/customProjectFields/{id}':
    get:
      tags:
        - Custom Project Fields
      summary: Get a Custom Project Field
      operationId: getCustomProjectField
      security:
        - loopio_auth:
            - 'customProjectField:read'
    patch:
      tags:
        - Custom Project Fields
      summary: Update a Custom Project Field
      operationId: updateCustomProjectField
      security:
        - loopio_auth:
            - 'customProjectField:write'
    delete:
      tags:
        - Custom Project Fields
      summary: Delete a Custom Project Field
      operationId: deleteCustomProjectField
      security:
        - loopio_auth:
            - 'customProjectField:delete'
  /projectEntries:
    get:
      tags:
        - Projects
      summary: List your Project Entries
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: listProjectEntries
      security:
        - loopio_auth:
            - 'project:read'
    post:
      tags:
        - Projects
      summary: Create a new Project Entry
      description: |-
        Create a new Project Entry.
        In addition to the projectId, one of either the sectionId or subSectionId must be provided, but not both. Note: Confidential projects are currently not supported via API.
      operationId: createProjectEntry
      security:
        - loopio_auth:
            - 'project:write'
  '/projectEntries/{projectEntryId}':
    get:
      tags:
        - Projects
      summary: Retrieve a specific Project Entry
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: getProjectEntry
      security:
        - loopio_auth:
            - 'project:read'
    put:
      tags:
        - Projects
      summary: Update a specific Project Entry
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: updateProjectEntry
      security:
        - loopio_auth:
            - 'project:write'
    delete:
      tags:
        - Projects
      summary: Delete a specific Project Entry
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: deleteProjectEntry
      security:
        - loopio_auth:
            - 'project:write'
  /sections:
    get:
      tags:
        - Projects
      summary: List your Project sections
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: listProjectSections
      security:
        - loopio_auth:
            - 'project:read'
    post:
      tags:
        - Projects
      summary: Create a new Project section
      description: |-
        Create a new Project section.

         Note: Confidential projects are currently not supported via API.
      operationId: createProjectSection
      security:
        - loopio_auth:
            - 'project:write'
  '/sections/{sectionId}':
    get:
      tags:
        - Projects
      summary: Retrieve a specific Project section
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: getProjectSection
      security:
        - loopio_auth:
            - 'project:read'
    put:
      tags:
        - Projects
      summary: Update a specific Project section
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: updateProjectSection
      security:
        - loopio_auth:
            - 'project:write'
    delete:
      tags:
        - Projects
      summary: Delete a Project section and its content
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: deleteProjectSection
      security:
        - loopio_auth:
            - 'project:write'
  /subSections:
    get:
      tags:
        - Projects
      summary: List your Project subSections
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: listProjectSubSections
      security:
        - loopio_auth:
            - 'project:read'
    post:
      tags:
        - Projects
      summary: Create a new Project subSection
      description: |-
        Create a new Project subSection.

         Note: Confidential projects are currently not supported via API.
      operationId: createProjectSubSection
      security:
        - loopio_auth:
            - 'project:write'
  '/subSections/{subSectionId}':
    get:
      tags:
        - Projects
      summary: Retrieve a specific Project subSection
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: getProjectSubQuestion
      security:
        - loopio_auth:
            - 'project:read'
    put:
      tags:
        - Projects
      summary: Update a specific Project subSection
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: updateProjectSubSection
      security:
        - loopio_auth:
            - 'project:write'
    delete:
      tags:
        - Projects
      summary: Delete a Project subSection and its content
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: deleteProjectSubSection
      security:
        - loopio_auth:
            - 'project:write'
  '/asyncTasks/{taskId}':
    get:
      tags:
        - Asynchronous
      summary: Get the status of a queued async request
      operationId: getAsyncStatus
  '/asyncTasks/{taskId}/projectTemplateCopy':
    get:
      tags:
        - Asynchronous
        - Projects
      summary: Get the status of a create project from template async task
      operationId: getProjectTemplateCopyAsyncStatus
  /teams:
    get:
      tags:
        - Teams
      summary: List all teams
      operationId: listTeams
      security:
        - loopio_auth:
            - 'user:read'
  '/teams/{teamId}':
    get:
      tags:
        - Teams
      summary: Get a team's data
      operationId: getTeam
      security:
        - loopio_auth:
            - 'user:read'
  /identify/me:
    get:
      tags:
        - Users
      summary: Get a User's information from a JWT
      operationId: identifyUser
      security:
        - loopio_auth:
            - 'user:read'
  /roles:
    get:
      tags:
        - Roles
      summary: List all user roles
      operationId: listRoles
      security:
        - loopio_auth:
            - 'role:read'
  '/roles/{roleId}':
    get:
      tags:
        - Roles
      summary: Get a user role
      operationId: getRole
      security:
        - loopio_auth:
            - 'role:read'
  /users:
    get:
      tags:
        - Users
      summary: List Users
      operationId: listUsers
      security:
        - loopio_auth:
            - 'user:read'
    post:
      tags:
        - Users
      summary: Create a User
      operationId: createUser
      security:
        - loopio_auth:
            - 'user:write'
  /users/bulk/disableByEmail:
    post:
      tags:
        - Users
      summary: Bulk disable Users by email
      description: |-
        This operation is atomic (either all Users will be successfully disabled or none will). Users are not able to disable themselves.

        To protect Customer privacy, emails that are not tied to a User will be ignored rather than treated as an input error.
      operationId: bulkUserDisableByEmail
      security:
        - loopio_auth:
            - 'user:write'
  '/users/{userId}':
    get:
      tags:
        - Users
      summary: Get a User
      operationId: getUser
      security:
        - loopio_auth:
            - 'user:read'
    put:
      tags:
        - Users
      summary: Update a User
      operationId: updateUser
      security:
        - loopio_auth:
            - 'user:write'
  /webhookSubscriptions:
    get:
      tags:
        - Webhooks
      summary: List your event subscriptions (webhooks)
      operationId: listWebhookSubscriptions
      security:
        - loopio_auth:
            - 'webhook:read'
    post:
      tags:
        - Webhooks
      summary: Create a new event subscription (new webhook)
      description: |-
        Callback URL validation as described [here](https://support.loopio.com/hc/en-us/articles/4404035824147-How-Do-I-Validate-My-Webhook-URL-) will occur automatically as part of this request.
        Help with handling webhook callback requests can be found [here](https://support.loopio.com/hc/en-us/articles/4404035409555-What-Information-is-in-a-Webhook-Event-Notification-)
      operationId: createWebhookSubscription
      security:
        - loopio_auth:
            - 'webhook:write'
  '/webhookSubscriptions/{subscriptionId}':
    get:
      tags:
        - Webhooks
      summary: Get event subscription details
      operationId: getWebhookSubscription
      security:
        - loopio_auth:
            - 'webhook:read'
    put:
      tags:
        - Webhooks
      summary: Change event subscription details
      operationId: updateWebhookSubscription
      security:
        - loopio_auth:
            - 'webhook:write'
    delete:
      tags:
        - Webhooks
      summary: Cancel an event subscription
      operationId: cancelWebhookSubscription
      security:
        - loopio_auth:
            - 'webhook:delete'
  '/webhookSubscriptions/{subscriptionId}/signingSecret':
    post:
      tags:
        - Webhooks
      summary: Refresh a webhook's signing secret to a new value
      operationId: refreshWebhookSigningSecret
      security:
        - loopio_auth:
            - 'webhook:write'
components:
  securitySchemes:
    loopio_auth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /oauth2/authorize
          tokenUrl: /oauth2/access_token
          scopes:
            'mergeVariable:read': View Merge Variables
            'mergeVariable:write': Create/Edit Merge Variables
            'mergeVariable:delete': Delete Merge Variables
            'crm:read': List CRM opportunities linked to projects
            'crm:write': Link CRM opportunities to projects
            'customer.info:read': View customer information
            'file:read': Download files and view file information
            'file:delete': Delete files
            'library:read': 'List Library Entries and stacks, view Library Entries and Entry data'
            'library:write': Create and update Library Entries and Entry data
            'library:delete': Delete Library Entries
            'project:read': 'List Projects, view Project data and source documents'
            'project:write': 'Create and update Projects, Project data, and source documents'
            'project:delete': Delete a Project
            'project.participant:read': List participants of a project
            'project.participant:write': Update participant information
            'role:read': List user assignable roles
            'user:read': 'List users, view user information'
            'user:write': Update user information
            'webhook:read': View webhook subscriptions
            'webhook:write': Create & edit webhook subscriptions
            'webhook:delete': Delete webhook subscriptions
        clientCredentials:
          tokenUrl: /oauth2/access_token
          scopes:
            'mergeVariable:read': View Merge Variables
            'mergeVariable:write': Create/Edit Merge Variables
            'mergeVariable:delete': Delete Merge Variables
            'crm:read': List CRM opportunities linked to projects
            'crm:write': Link CRM opportunities to projects
            'customer.info:read': View customer information
            'file:read': Download files and view file information
            'file:delete': Delete files
            'library:read': 'List Library Entries and stacks, view Library Entries and Entry data'
            'library:write': Create and update Library Entries and Entry data
            'library:delete': Delete Library Entries
            'project:read': 'List Projects, view Project data and source documents'
            'project:write': 'Create and update Projects, Project data, and source documents'
            'project:delete': Delete a Project
            'project.participant:read': List participants of a project
            'project.participant:write': Update participant information
            'role:read': List user assignable roles
            'user:read': 'List users, view user information'
            'user:write': Update user information
            'webhook:read': View webhook subscriptions
            'webhook:write': Create & edit webhook subscriptions
            'webhook:delete': Delete webhook subscriptions