openapi: 3.0.1
info:
  title: Loopio
  description: Loopio's Public API
  termsOfService: 'http://loopio.com/termsOfService'
  contact:
    email: support@loopio.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0
servers:
  - url: 'https://api.loopio.com/data/v2'
    description: Production server for the American datacenter
tags:
  - name: Asynchronous
    description: An asynchronous endpoint
  - name: Custom Project Fields
    description: Create and manage Custom Project Fields
  - name: Files
    description: Manage Loopio files
  - name: Library Entries
    description: Create and manage Library Entries
  - name: Projects
    description: Create and manage Projects
  - name: Project Templates
    description: Get Information about Project Templates
  - name: Stacks
    description: View accessible stacks or Library structure
paths:
  '/customers/{customerId}/activeLanguages':
  '/customers/{customerId}':
  '/files/{fileId}':
    get:
      tags:
        - Files
      summary: Show information about a file
      operationId: showFile
      security:
        - loopio_auth:
            - 'file:read'
    delete:
      tags:
        - Files
      summary: Delete a file
      description: 'If this file is linked with any other Loopio resources, that link will also be deleted'
      operationId: deleteFile
      security:
        - loopio_auth:
            - 'file:delete'
  /libraryEntries:
    get:
      tags:
        - Library Entries
      summary: List Library Entries you can interact with
      operationId: listLibraryEntries
      security:
        - loopio_auth:
            - 'library:read'
    post:
      tags:
        - Library Entries
      summary: Create a Library Entry
      description: |-
        Answer text for an Entry can be null if its Questions have Compliance Answers.
        Note: we are making terminology updates in Loopio - Compliance Sets shall be referred to as Answer Sets. The API will be updated to reflect this change at a later time.
      operationId: createLibraryEntry
      security:
        - loopio_auth:
            - 'library:write'
  /libraryEntries/bulk:
    post:
      tags:
        - Library Entries
        - Asynchronous
      summary: Bulk create Library Entries
      description: |-
        Answer text for an Entry can be null if its Questions have Compliance Answers.
        Note: we are making terminology updates in Loopio - Compliance Sets shall be referred to as Answer Sets. The API will be updated to reflect this change at a later time.
      operationId: bulkCreateLibraryEntries
      security:
        - loopio_auth:
            - 'library:write'
  '/libraryEntries/{libraryEntryId}':
    get:
      tags:
        - Library Entries
      summary: Get a Library Entry
      operationId: getLibraryEntry
      security:
        - loopio_auth:
            - 'library:read'
    patch:
      tags:
        - Library Entries
      summary: Update core properties of a Library Entry
      operationId: updateLibraryEntry
      security:
        - loopio_auth:
            - 'library:write'
    delete:
      tags:
        - Library Entries
      operationId: deleteLibraryEntry
      security:
        - loopio_auth:
            - 'library:delete'
  '/libraryEntries/{libraryEntryId}/attachments':
    get:
      tags:
        - Library Entries
      summary: Get Library Entry's Attachments
      operationId: getLibraryEntryFiles
      security:
        - loopio_auth:
            - 'library:read'
  '/libraryEntryHistories/{libraryEntryId}':
    get:
      tags:
        - Library Entries
      summary: Get history of a Library Entry
      operationId: getLibraryEntryHistories
      security:
        - loopio_auth:
            - 'library:read'
  '/libraryEntryHistories/{libraryEntryId}/{historyId}':
    get:
      tags:
        - Library Entries
      summary: Get a specific history item of a Library Entry
      operationId: getLibraryEntryHistory
      security:
        - loopio_auth:
            - 'library:read'
  /stacks:
    get:
      tags:
        - Stacks
      summary: List accessible stacks; View full Library structure
      operationId: listStacks
      security:
        - loopio_auth:
            - 'library:read'
  '/projects/{projectId}/complianceSets':
    get:
      tags:
        - Projects
      summary: Get the Compliance Sets for a Project
      description: |-
        Note: Confidential projects are currently not supported via API.

         Note: We are making terminology updates in Loopio - Compliance Sets shall be referred to as Answer Sets. The API will be updated to reflect this change at a later time.
      operationId: getProjectComplianceSets
    post:
      tags:
        - Projects
      summary: Create a Compliance Set for a Project
      description: |-
        Note: Confidential projects are currently not supported via API.

         Note: We are making terminology updates in Loopio - Compliance Sets shall be referred to as Answer Sets. The API will be updated to reflect this change at a later time.
      operationId: createComplianceSet
  '/projects/{projectId}/complianceSets/{complianceSetId}':
    get:
      tags:
        - Projects
      summary: Get a Compliance Set for a Project
      description: |-
        Note: Confidential projects are currently not supported via API.

         Note: We are making terminology updates in Loopio - Compliance Sets shall be referred to as Answer Sets.  The API will be updated to reflect this change at a later time.
      operationId: getProjectComplianceSet
    put:
      tags:
        - Projects
      summary: Update a Compliance Set for a Project
      description: |-
        Note: Confidential projects are currently not supported via API.

         Note: We are making terminology updates in Loopio - Compliance Sets shall be referred to as Answer Sets. The API will be updated to reflect this change at a later time.
      operationId: updateProjectComplianceSet
    delete:
      tags:
        - Projects
      summary: Delete a Compliance Set for a Project
      description: |-
        Note: Confidential projects are currently not supported via API.

         Note: We are making terminology updates in Loopio - Compliance Sets shall be referred to as Answer Sets. The API will be updated to reflect this change at a later time.
      operationId: deleteProjectComplianceSet
  /projects:
    get:
      tags:
        - Projects
      summary: List projects you can interact with
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: listProjects
      security:
        - loopio_auth:
            - 'project:read'
    post:
      tags:
        - Projects
      summary: Create a project
      operationId: createProject
      security:
        - loopio_auth:
            - 'project:write'
  '/projects/{projectId}':
    get:
      tags:
        - Projects
      summary: Get a Project's data
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: getProject
      security:
        - loopio_auth:
            - 'project:read'
    put:
      tags:
        - Projects
      summary: Update a Project's status
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: updateProject
      security:
        - loopio_auth:
            - 'project:write'
    delete:
      tags:
        - Projects
      summary: Delete a Project and its data
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: deleteProject
      security:
        - loopio_auth:
            - 'project:delete'
  '/projects/{projectId}/customProjectFields':
    get:
      tags:
        - Projects
        - Custom Project Fields
      summary: Get Custom Project Field values for a given Project
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: getCustomProjectFieldValuesForProject
      security:
        - loopio_auth:
            - 'project:read'
    patch:
      tags:
        - Projects
        - Custom Project Fields
      summary: Edit Custom Project Field values for a given Project
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: setCustomProjectFieldValuesForProject
      security:
        - loopio_auth:
            - 'project:write'
  '/projects/{projectId}/summary':
    get:
      tags:
        - Projects
      summary: Get the status summary of a Project
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: getProjectSummary
      security:
        - loopio_auth:
            - 'project:read'
  /projects/summary:
    get:
      tags:
        - Projects
      summary: Get the status summary list of Projects filtered by date last synced
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: getProjectSummaryList
      security:
        - loopio_auth:
            - 'project:read'
  '/projects/{projectId}/sourceDocuments':
    post:
      tags:
        - Projects
        - Files
      summary: Attach a source document to a Loopio Project
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: addProjectSourceDocument
      security:
        - loopio_auth:
            - 'project:write'
    get:
      tags:
        - Projects
        - Files
      summary: View basic information on a Project's source files
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: listProjectSourceDocuments
      security:
        - loopio_auth:
            - 'project:read'
  '/projects/{projectId}/participants':
    get:
      tags:
        - Projects
      summary: Get the participants for a Project
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: getProjectParticipants
      security:
        - loopio_auth:
            - 'project.participant:read'
    put:
      tags:
        - Projects
      summary: Update the participants for a Project
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: updateProjectParticipants
      security:
        - loopio_auth:
            - 'project.participant:write'
  '/projectTemplates/{projectTemplateId}/projects':
    post:
      tags:
        - Projects
      summary: Create a project using a template (This creates an async task to execute this operation)
      description: 'Returns a taskId and a projectId. Make a GET request to /asyncTasks/{taskId}/projectTemplateCopy to find the status of the task.'
      operationId: createProjectFromTemplate
      security:
        - loopio_auth:
            - 'project:write'
  /projectTemplates:
    get:
      tags:
        - Project Templates
      summary: Get a list of published project templates
      operationId: listProjectTemplates
      security:
        - loopio_auth:
            - 'project:read'
  /customProjectFields:
    get:
      tags:
        - Custom Project Fields
      summary: List defined Custom Project Fields
      operationId: listCustomProjectFields
      security:
        - loopio_auth:
            - 'customProjectField:read'
    post:
      tags:
        - Custom Project Fields
      summary: Create a new Custom Project Field
      operationId: createCustomProjectField
      security:
        - loopio_auth:
            - 'customProjectField:write'
  '/customProjectFields/{id}':
    get:
      tags:
        - Custom Project Fields
      summary: Get a Custom Project Field
      operationId: getCustomProjectField
      security:
        - loopio_auth:
            - 'customProjectField:read'
    patch:
      tags:
        - Custom Project Fields
      summary: Update a Custom Project Field
      operationId: updateCustomProjectField
      security:
        - loopio_auth:
            - 'customProjectField:write'
    delete:
      tags:
        - Custom Project Fields
      summary: Delete a Custom Project Field
      operationId: deleteCustomProjectField
      security:
        - loopio_auth:
            - 'customProjectField:delete'
  /projectEntries:
    get:
      tags:
        - Projects
      summary: List your Project Entries
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: listProjectEntries
      security:
        - loopio_auth:
            - 'project:read'
    post:
      tags:
        - Projects
      summary: Create a new Project Entry
      description: |-
        Create a new Project Entry.
        In addition to the projectId, one of either the sectionId or subSectionId must be provided, but not both. Note: Confidential projects are currently not supported via API.
      operationId: createProjectEntry
      security:
        - loopio_auth:
            - 'project:write'
  '/projectEntries/{projectEntryId}':
    get:
      tags:
        - Projects
      summary: Retrieve a specific Project Entry
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: getProjectEntry
      security:
        - loopio_auth:
            - 'project:read'
    put:
      tags:
        - Projects
      summary: Update a specific Project Entry
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: updateProjectEntry
      security:
        - loopio_auth:
            - 'project:write'
    delete:
      tags:
        - Projects
      summary: Delete a specific Project Entry
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: deleteProjectEntry
      security:
        - loopio_auth:
            - 'project:write'
  /sections:
    get:
      tags:
        - Projects
      summary: List your Project sections
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: listProjectSections
      security:
        - loopio_auth:
            - 'project:read'
    post:
      tags:
        - Projects
      summary: Create a new Project section
      description: |-
        Create a new Project section.

         Note: Confidential projects are currently not supported via API.
      operationId: createProjectSection
      security:
        - loopio_auth:
            - 'project:write'
  '/sections/{sectionId}':
    get:
      tags:
        - Projects
      summary: Retrieve a specific Project section
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: getProjectSection
      security:
        - loopio_auth:
            - 'project:read'
    put:
      tags:
        - Projects
      summary: Update a specific Project section
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: updateProjectSection
      security:
        - loopio_auth:
            - 'project:write'
    delete:
      tags:
        - Projects
      summary: Delete a Project section and its content
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: deleteProjectSection
      security:
        - loopio_auth:
            - 'project:write'
  /subSections:
    get:
      tags:
        - Projects
      summary: List your Project subSections
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: listProjectSubSections
      security:
        - loopio_auth:
            - 'project:read'
    post:
      tags:
        - Projects
      summary: Create a new Project subSection
      description: |-
        Create a new Project subSection.

         Note: Confidential projects are currently not supported via API.
      operationId: createProjectSubSection
      security:
        - loopio_auth:
            - 'project:write'
  '/subSections/{subSectionId}':
    get:
      tags:
        - Projects
      summary: Retrieve a specific Project subSection
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: getProjectSubQuestion
      security:
        - loopio_auth:
            - 'project:read'
    put:
      tags:
        - Projects
      summary: Update a specific Project subSection
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: updateProjectSubSection
      security:
        - loopio_auth:
            - 'project:write'
    delete:
      tags:
        - Projects
      summary: Delete a Project subSection and its content
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: deleteProjectSubSection
      security:
        - loopio_auth:
            - 'project:write'
components:
  securitySchemes:
    loopio_auth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /oauth2/authorize
          tokenUrl: /oauth2/access_token
          scopes:
            'mergeVariable:read': View Merge Variables
            'mergeVariable:write': Create/Edit Merge Variables
            'mergeVariable:delete': Delete Merge Variables
            'crm:read': List CRM opportunities linked to projects
            'crm:write': Link CRM opportunities to projects
            'customer.info:read': View customer information
            'file:read': Download files and view file information
            'file:delete': Delete files
            'library:read': 'List Library Entries and stacks, view Library Entries and Entry data'
            'library:write': Create and update Library Entries and Entry data
            'library:delete': Delete Library Entries
            'project:read': 'List Projects, view Project data and source documents'
            'project:write': 'Create and update Projects, Project data, and source documents'
            'project:delete': Delete a Project
            'project.participant:read': List participants of a project
            'project.participant:write': Update participant information
            'role:read': List user assignable roles
            'user:read': 'List users, view user information'
            'user:write': Update user information
            'webhook:read': View webhook subscriptions
            'webhook:write': Create & edit webhook subscriptions
            'webhook:delete': Delete webhook subscriptions
        clientCredentials:
          tokenUrl: /oauth2/access_token
          scopes:
            'mergeVariable:read': View Merge Variables
            'mergeVariable:write': Create/Edit Merge Variables
            'mergeVariable:delete': Delete Merge Variables
            'crm:read': List CRM opportunities linked to projects
            'crm:write': Link CRM opportunities to projects
            'customer.info:read': View customer information
            'file:read': Download files and view file information
            'file:delete': Delete files
            'library:read': 'List Library Entries and stacks, view Library Entries and Entry data'
            'library:write': Create and update Library Entries and Entry data
            'library:delete': Delete Library Entries
            'project:read': 'List Projects, view Project data and source documents'
            'project:write': 'Create and update Projects, Project data, and source documents'
            'project:delete': Delete a Project
            'project.participant:read': List participants of a project
            'project.participant:write': Update participant information
            'role:read': List user assignable roles
            'user:read': 'List users, view user information'
            'user:write': Update user information
            'webhook:read': View webhook subscriptions
            'webhook:write': Create & edit webhook subscriptions
            'webhook:delete': Delete webhook subscriptions