openapi: 3.0.1
info:
  title: Loopio
  description: Loopio's Public API
  termsOfService: 'http://loopio.com/termsOfService'
  contact:
    email: support@loopio.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0
servers:
  - url: 'https://api.loopio.com/data/v2'
    description: Production server for the American datacenter
tags:
  - name: Customers
    description: Get information about Customer instances
  - name: Custom Project Fields
    description: Create and manage Custom Project Fields
  - name: Files
    description: Manage Loopio files
  - name: Library Entries
    description: Create and manage Library Entries
  - name: Projects
    description: Create and manage Projects
  - name: Project Templates
    description: Get Information about Project Templates
  - name: Stacks
    description: View accessible stacks or Library structure
paths:
  '/customers/{customerId}/activeLanguages':
    get:
      tags:
        - Customers
      summary: Get all the languages in use in a customer's collection of library entries
      operationId: getCustomerActiveLanguages
      security:
        - loopio_auth:
            - 'customer.info:read'
  '/customers/{customerId}':
    get:
      tags:
        - Customers
      summary: Get the id and guid for a given Customer
      operationId: getCustomer
      security:
        - loopio_auth:
            - 'customer.info:read'
  '/files/{fileId}':
    get:
      tags:
        - Files
      summary: Show information about a file
      operationId: showFile
      security:
        - loopio_auth:
            - 'file:read'
  '/crm/{opportunityID}/projects':
    get:
      tags:
        - CRM
      summary: Get the list of viewable Projects associated with a given CRM Opportunity
      operationId: listCRMProjects
      security:
        - loopio_auth:
            - 'crm:read'
  /libraryEntries:
    get:
      tags:
        - Library Entries
      summary: List Library Entries you can interact with
      operationId: listLibraryEntries
      security:
        - loopio_auth:
            - 'library:read'
  '/libraryEntries/{libraryEntryId}':
    get:
      tags:
        - Library Entries
      summary: Get a Library Entry
      operationId: getLibraryEntry
      security:
        - loopio_auth:
            - 'library:read'
  '/libraryEntries/{libraryEntryId}/attachments':
    get:
      tags:
        - Library Entries
      summary: Get Library Entry's Attachments
      operationId: getLibraryEntryFiles
      security:
        - loopio_auth:
            - 'library:read'
  '/libraryEntryHistories/{libraryEntryId}':
    get:
      tags:
        - Library Entries
      summary: Get history of a Library Entry
      operationId: getLibraryEntryHistories
      security:
        - loopio_auth:
            - 'library:read'
  '/libraryEntryHistories/{libraryEntryId}/{historyId}':
    get:
      tags:
        - Library Entries
      summary: Get a specific history item of a Library Entry
      operationId: getLibraryEntryHistory
      security:
        - loopio_auth:
            - 'library:read'
  /stacks:
    get:
      tags:
        - Stacks
      summary: List accessible stacks; View full Library structure
      operationId: listStacks
      security:
        - loopio_auth:
            - 'library:read'
  '/projects/{projectId}/complianceSets':
    get:
      tags:
        - Projects
      summary: Get the Compliance Sets for a Project
      description: |-
        Note: Confidential projects are currently not supported via API.

         Note: We are making terminology updates in Loopio - Compliance Sets shall be referred to as Answer Sets. The API will be updated to reflect this change at a later time.
      operationId: getProjectComplianceSets
  '/projects/{projectId}/complianceSets/{complianceSetId}':
    get:
      tags:
        - Projects
      summary: Get a Compliance Set for a Project
      description: |-
        Note: Confidential projects are currently not supported via API.

         Note: We are making terminology updates in Loopio - Compliance Sets shall be referred to as Answer Sets.  The API will be updated to reflect this change at a later time.
      operationId: getProjectComplianceSet
  /projects:
    get:
      tags:
        - Projects
      summary: List projects you can interact with
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: listProjects
      security:
        - loopio_auth:
            - 'project:read'
  '/projects/{projectId}':
    get:
      tags:
        - Projects
      summary: Get a Project's data
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: getProject
      security:
        - loopio_auth:
            - 'project:read'
  '/projects/{projectId}/customProjectFields':
    get:
      tags:
        - Projects
        - Custom Project Fields
      summary: Get Custom Project Field values for a given Project
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: getCustomProjectFieldValuesForProject
      security:
        - loopio_auth:
            - 'project:read'
  '/projects/{projectId}/summary':
    get:
      tags:
        - Projects
      summary: Get the status summary of a Project
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: getProjectSummary
      security:
        - loopio_auth:
            - 'project:read'
  /projects/summary:
    get:
      tags:
        - Projects
      summary: Get the status summary list of Projects filtered by date last synced
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: getProjectSummaryList
      security:
        - loopio_auth:
            - 'project:read'
  '/projects/{projectId}/sourceDocuments':
    get:
      tags:
        - Projects
        - Files
      summary: View basic information on a Project's source files
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: listProjectSourceDocuments
      security:
        - loopio_auth:
            - 'project:read'
  '/projects/{projectId}/participants':
    get:
      tags:
        - Projects
      summary: Get the participants for a Project
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: getProjectParticipants
      security:
        - loopio_auth:
            - 'project.participant:read'
  /customProjectFields:
    get:
      tags:
        - Custom Project Fields
      summary: List defined Custom Project Fields
      operationId: listCustomProjectFields
      security:
        - loopio_auth:
            - 'customProjectField:read'
  '/customProjectFields/{id}':
    get:
      tags:
        - Custom Project Fields
      summary: Get a Custom Project Field
      operationId: getCustomProjectField
      security:
        - loopio_auth:
            - 'customProjectField:read'
  /projectEntries:
    get:
      tags:
        - Projects
      summary: List your Project Entries
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: listProjectEntries
      security:
        - loopio_auth:
            - 'project:read'
  '/projectEntries/{projectEntryId}':
    get:
      tags:
        - Projects
      summary: Retrieve a specific Project Entry
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: getProjectEntry
      security:
        - loopio_auth:
            - 'project:read'
  /sections:
    get:
      tags:
        - Projects
      summary: List your Project sections
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: listProjectSections
      security:
        - loopio_auth:
            - 'project:read'
  '/sections/{sectionId}':
    get:
      tags:
        - Projects
      summary: Retrieve a specific Project section
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: getProjectSection
      security:
        - loopio_auth:
            - 'project:read'
  /subSections:
    get:
      tags:
        - Projects
      summary: List your Project subSections
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: listProjectSubSections
      security:
        - loopio_auth:
            - 'project:read'
  '/subSections/{subSectionId}':
    get:
      tags:
        - Projects
      summary: Retrieve a specific Project subSection
      description: 'Note: Confidential projects are currently not supported via API.'
      operationId: getProjectSubQuestion
      security:
        - loopio_auth:
            - 'project:read'
  '/webhookSubscriptions/{subscriptionId}':
  '/webhookSubscriptions/{subscriptionId}/signingSecret':
components:
  securitySchemes:
    loopio_auth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /oauth2/authorize
          tokenUrl: /oauth2/access_token
          scopes:
            'mergeVariable:read': View Merge Variables
            'mergeVariable:write': Create/Edit Merge Variables
            'mergeVariable:delete': Delete Merge Variables
            'crm:read': List CRM opportunities linked to projects
            'crm:write': Link CRM opportunities to projects
            'customer.info:read': View customer information
            'file:read': Download files and view file information
            'file:delete': Delete files
            'library:read': 'List Library Entries and stacks, view Library Entries and Entry data'
            'library:write': Create and update Library Entries and Entry data
            'library:delete': Delete Library Entries
            'project:read': 'List Projects, view Project data and source documents'
            'project:write': 'Create and update Projects, Project data, and source documents'
            'project:delete': Delete a Project
            'project.participant:read': List participants of a project
            'project.participant:write': Update participant information
            'role:read': List user assignable roles
            'user:read': 'List users, view user information'
            'user:write': Update user information
            'webhook:read': View webhook subscriptions
            'webhook:write': Create & edit webhook subscriptions
            'webhook:delete': Delete webhook subscriptions
        clientCredentials:
          tokenUrl: /oauth2/access_token
          scopes:
            'mergeVariable:read': View Merge Variables
            'mergeVariable:write': Create/Edit Merge Variables
            'mergeVariable:delete': Delete Merge Variables
            'crm:read': List CRM opportunities linked to projects
            'crm:write': Link CRM opportunities to projects
            'customer.info:read': View customer information
            'file:read': Download files and view file information
            'file:delete': Delete files
            'library:read': 'List Library Entries and stacks, view Library Entries and Entry data'
            'library:write': Create and update Library Entries and Entry data
            'library:delete': Delete Library Entries
            'project:read': 'List Projects, view Project data and source documents'
            'project:write': 'Create and update Projects, Project data, and source documents'
            'project:delete': Delete a Project
            'project.participant:read': List participants of a project
            'project.participant:write': Update participant information
            'role:read': List user assignable roles
            'user:read': 'List users, view user information'
            'user:write': Update user information
            'webhook:read': View webhook subscriptions
            'webhook:write': Create & edit webhook subscriptions
            'webhook:delete': Delete webhook subscriptions